#!/bin/bash
export CMD=""
. ~/set-enviornment.sh

if [ -z "$1" ]; then
  echo "usage: chef <domain> <service> <verb>-<noun> <args>"
  exit 1
fi

if [ $1 == "node" ]; then
    export CMD="node"
fi

if [ $1 == "courier" ]; then
    export CMD="courier"
fi

if [ -z "$CMD" ]; then
  echo "$1 is Invalid service domain"
  echo "Valid options:"
  echo "node"
  echo "courier"
  exit 1
fi

~/cmd/$CMD "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9"
