#!/bin/bash
if [ -z "$PLATFORM_URL" ]; then
  echo "PLATFORM_URL is not configured"
  exit 1
fi


if [ -z "$1" ]; then
  echo "usage: courier scheduler estimate-schedule <UUID> <COUNT>"
  exit 0;
fi


if [ $(curl -LI -X HEAD $PLATFORM_URL:$COURIER_SCHEDULER_PORT/job/$1 -o /dev/null -w '%{http_code}\n' -s) == "200" ]; then 
  export IMMEDIATE=$(curl -s $PLATFORM_URL:$COURIER_SCHEDULER_PORT/job/$1 | jq '.immediate')

  if [ "$IMMEDIATE" == "true" ]; then
    echo "can not esimate a schedule for an immediate job"
  else
    if [ -z "$2" ]; then
      curl -s $PLATFORM_URL:$COURIER_SCHEDULER_PORT/job/$1/estimate?count=10 | jq
    else
      curl -s $PLATFORM_URL:$COURIER_SCHEDULER_PORT/job/$1/estimate?count=$2 | jq
    fi
  fi
fi

