#!/bin/bash
. ~/set-enviornment.sh
echo "usage: courier delivery delete-channels"
echo "This feature is not supported by your message queue provider."
echo "Courier delivery is configured with 0MQ (ZeroMQ)."
exit 1
