#!/bin/bash
export CMD=""
if [ -z "$PLATFORM_URL" ]; then
  echo "PLATFORM_URL is not configured"
  exit 1
fi
if [ -z "$1" ]; then
  echo "usage: courier state <verb>-<noun> <args>"
  exit 1
fi

if [ $1 == "list-job-instances" ]; then
    export CMD="list-job-instances"
fi

if [ $1 == "list-job-instance-runs" ]; then
    export CMD="list-job-instance-runs"
fi

if [ $1 == "get-job-run" ]; then
    export CMD="get-job-run"
fi

if [ $1 == "list-job-run-steps" ]; then
    export CMD="list-job-run-steps"
fi

if [ $1 == "get-job-instance" ]; then
    export CMD="get-job-instance"
fi


if [ -z "$CMD" ]; then
  echo "usage: courier state <verb>-<noun> <args>"
  echo "$1 is Invalid action expected: <verb>-<noun>"
  echo "Valid options:"
  echo "list-job-instances"
  #echo "list-job-instance-runs"
  echo "get-job-run"
  echo "list-job-run-steps"
  #echo "get-job-instance"
  exit 1
fi

/opt/demo/courier_state_$CMD "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9"
