#!/bin/bash
export CMD=""
if [ -z "$PLATFORM_URL" ]; then
  echo "PLATFORM_URL is not configured"
  exit 1
fi

if [ $1 == "running-jobs" ]; then
    export CMD="running-jobs"
fi




if [ -z "$CMD" ]; then
  echo "usage: courier orchestrator <verb>-<noun> <args>"
  echo "$1 is Invalid action expected: <verb>-<noun>"
  echo "Valid options:"
  echo "list-jobs"
  exit 1
fi

/opt/demo/courier_orchestrator_$CMD "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9"
