#!/bin/bash
if [ -z "$PLATFORM_URL" ]; then
  echo "PLATFORM_URL is not configured"
  exit 1
fi

echo "usage: courier delivery get-channel <NODEID>"
echo "This feature is not supported by your message queue provider."
echo "Courier delivery is configured with 0MQ (ZeroMQ)."
exit 1
