#!/bin/bash
if [ -z "$PLATFORM_URL" ]; then
  echo "PLATFORM_URL is not configured"
  exit 1
fi

export CMD=""

if [ -z "$1" ]; then
  echo "usage: courier scheduler delete-job <UUID>"
  exit 0;
fi


if [ $(curl -LI -X DELETE $PLATFORM_URL:$COURIER_SCHEDULER_PORT/job/$1 -o /dev/null -w '%{http_code}\n' -s) == "200" ]; then 
  echo "Deleted"; 
else
  echo "Not Found"; 
fi