#!/bin/bash
if [ -z "$PLATFORM_URL" ]; then
  echo "PLATFORM_URL is not configured"
  exit 1
fi


echo "usage: courier state <verb>-<noun> <args>"
echo "courier state is disabled for this demo enviornment"
exit 1
