#!/bin/bash
if [ -z "$PLATFORM_URL" ]; then
  echo "PLATFORM_URL is not configured"
  exit 1
fi

if [ -z "$1" ]; then
  curl -s $PLATFORM_URL:$NODE_MANAGER_PORT/v1/nodes/ | jq '.data[] | .id'
  exit 0;
fi

if [ $1 == "--help" ]; then
    echo "usage: node node list-nodes"
    echo "Flags"
    echo "--help"
    echo "--json"
    exit 0
fi

if [ $1 == "--json" ]; then
  curl -s $PLATFORM_URL:$NODE_MANAGER_PORT/v1/nodes/ | jq
  exit 0
fi

if [ $1 == "--raw" ]; then
  curl -s $PLATFORM_URL:$NODE_MANAGER_PORT/v1/nodes/ | jq
  exit 0
fi