#!/bin/bash

if [ -z "$1" ]; then
  echo "usage: node node get-node <UUID>"
  exit 0;
fi


if [ -z "$2" ]; then
    export status="OK"
else
  curl -s $PLATFORM_URL:$NODE_MANAGER_PORT/v1/nodes/$1 | jq ".data.installed_skills[] | select(.name==\""$2"\") | ."
  exit 0;
fi



if [ -z "$1" ]; then
    export status="OK"
else
  curl -s $PLATFORM_URL:$NODE_MANAGER_PORT/v1/nodes/$1 | jq '.data.installed_skills'
  exit 0;
fi

