#!/bin/bash
if [ -z "$PLATFORM_URL" ]; then
  echo "PLATFORM_URL is not configured"
  exit 1
fi

if [ -z "$1" ]; then
  echo "usage: node node get-node <UUID>"
  exit 0;
fi

if [ $1 == "--help" ]; then
    echo "usage: node node get-node <UUID>"
    echo "Flags"
    echo "--help"
    echo "--json"
    exit 0
fi

if [ "$2" == "--json" ]; then
  curl -s $PLATFORM_URL:$NODE_MANAGER_PORT/v1/nodes/$1 | jq
  exit 0
fi

if [ "$2" == "--help" ]; then
    echo "usage: node node get-node $1"
    echo "Flags"
    echo "--help"
    echo "--json"
    exit 0
fi

if [ -z "$1" ]; then
    export status="OK"
else
  curl -s $PLATFORM_URL:$NODE_MANAGER_PORT/v1/nodes/$1 | jq '{ id: .id, hostname: (.attributes[] | select(.name=="hostname") | .value)}'
  exit 0;
fi

