#!/bin/bash
export CMD=""

if [ -z "$1" ]; then
  echo "usage: node node <verb>-<noun> <args>"
  exit 1
fi

if [ $1 == "list-nodes" ]; then
    export CMD="list-nodes"
fi

if [ $1 == "get-node" ]; then
    export CMD="get-node"
fi

if [ $1 == "list-skills" ]; then
    export CMD="list-skills"
fi

if [ $1 == "assign-skill" ]; then
    export CMD="assign-skill"
fi

if [ $1 == "remove-skill" ]; then
    export CMD="remove-skill"
fi


if [ -z "$CMD" ]; then
  echo "usage: node skill <verb>-<noun> <args>"
  echo "$1 is Invalid action expected: <verb>-<noun>"
  echo "Valid options:"
  echo "list-nodes"
  echo "get-node"
  echo "list-skills"
  echo "assign-skill"
  echo "remove-skill"
  exit 1
fi

~/cmd/node_node_$CMD "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9"